#!/usr/bin/env python3
"""Find the headshot rings in a reference chart image.

Writes a source-layout.yaml recording where each face sits in that image,
which scripts/extract-headshots.py then crops from. Rings are found as dark
connected components with a square, headshot-sized bounding box; each is
matched to the nearest id in the existing layout file, so the ids survive a
re-detection against a new reference render.

    scripts/detect-faces.py reference/usmcc-leadership-nov2025.png
"""

from __future__ import annotations

import argparse
import math
import sys
from collections import deque
from pathlib import Path

import yaml
from PIL import Image

REPO = Path(__file__).resolve().parents[1]


def components(mask: bytearray, w: int, h: int):
    seen = bytearray(w * h)
    for y in range(h):
        for x in range(w):
            i = y * w + x
            if not mask[i] or seen[i]:
                continue
            queue = deque([(x, y)])
            seen[i] = 1
            x0 = x1 = x
            y0 = y1 = y
            count = 0
            while queue:
                cx, cy = queue.popleft()
                count += 1
                x0, x1 = min(x0, cx), max(x1, cx)
                y0, y1 = min(y0, cy), max(y1, cy)
                for dx, dy in ((1, 0), (-1, 0), (0, 1), (0, -1)):
                    nx, ny = cx + dx, cy + dy
                    if 0 <= nx < w and 0 <= ny < h:
                        j = ny * w + nx
                        if mask[j] and not seen[j]:
                            seen[j] = 1
                            queue.append((nx, ny))
            yield count, x0, y0, x1, y1


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("source", type=Path)
    ap.add_argument("--layout", type=Path,
                    default=REPO / "config" / "source-layout.yaml",
                    help="layout file to read ids from and rewrite")
    ap.add_argument("--threshold", type=int, default=150,
                    help="luminance below which a pixel counts as ink")
    ap.add_argument("--min-radius", type=int, default=40)
    ap.add_argument("--max-radius", type=int, default=68)
    ap.add_argument("--ring-inset", type=int, default=4,
                    help="shrink each radius by this much to drop the ring "
                         "stroke from the crop")
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args(argv)

    with Image.open(args.source) as src:
        rgba = src.convert("RGBA")
    # the reference is transparent, so flatten before thresholding or every
    # background pixel reads as ink
    flat = Image.new("RGBA", rgba.size, (255, 255, 255, 255))
    flat.alpha_composite(rgba)
    grey = flat.convert("L")
    w, h = grey.size
    px = grey.load()
    mask = bytearray(w * h)
    for y in range(h):
        row = y * w
        for x in range(w):
            mask[row + x] = 1 if px[x, y] < args.threshold else 0

    lo, hi = 2 * args.min_radius, 2 * args.max_radius
    rings = []
    for count, x0, y0, x1, y1 in components(mask, w, h):
        bw, bh = x1 - x0 + 1, y1 - y0 + 1
        if lo <= bw <= hi and lo <= bh <= hi and abs(bw - bh) <= 8 and count > 500:
            rings.append(((x0 + x1) / 2, (y0 + y1) / 2, (bw + bh) / 4))
    print(f"detected {len(rings)} ring(s) in {args.source.name}")

    previous = yaml.safe_load(args.layout.read_text()) if args.layout.exists() else {}
    known = previous.get("faces", {})
    scale = w / previous.get("canvas", [w, h])[0] if known else 1.0

    faces, used = {}, set()
    for cx, cy, r in sorted(rings, key=lambda c: (round(c[1] / 40), c[0])):
        best, dist = None, math.inf
        for pid, (kx, ky, _kr) in known.items():
            if pid in used:
                continue
            d = math.hypot(cx - kx * scale, cy - ky * scale)
            if d < dist:
                best, dist = pid, d
        if best is None or dist > 60:
            print(f"  unmatched ring at ({cx:.0f}, {cy:.0f}) r={r:.0f} — "
                  f"name it by hand", file=sys.stderr)
            continue
        used.add(best)
        faces[best] = [round(cx), round(cy), round(r) - args.ring_inset]
    for pid in known:
        if pid not in faces:
            print(f"  no ring found for {pid}", file=sys.stderr)

    body = yaml.safe_dump({"canvas": [w, h], "faces": faces},
                          sort_keys=False, default_flow_style=None)
    header = (f"# Generated by scripts/detect-faces.py from "
              f"{args.source.name}.\n"
              "#\n"
              "# Where each face sits in the reference chart image, in that\n"
              "# image's own coordinate space, with the ring stroke trimmed\n"
              "# off each radius. Used only by extract-headshots.py; the live\n"
              "# layout in chart.yaml has moved on from these positions.\n")
    if args.dry_run:
        print(header + body)
    else:
        args.layout.write_text(header + body)
        print(f"wrote {args.layout.relative_to(REPO)} with {len(faces)} face(s)")
    return 0 if len(faces) == len(known or faces) else 1


if __name__ == "__main__":
    raise SystemExit(main())
